/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meizu_jni_JniUtil */

#ifndef _Included_com_meizu_jni_JniUtil
#define _Included_com_meizu_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_meizu_jni_JniUtil_ENCRYPT_MODE
#define com_meizu_jni_JniUtil_ENCRYPT_MODE 1L
#undef com_meizu_jni_JniUtil_DECRYPT_MODE
#define com_meizu_jni_JniUtil_DECRYPT_MODE 2L
#undef com_meizu_jni_JniUtil_APP_SIGN_TYPE
#define com_meizu_jni_JniUtil_APP_SIGN_TYPE 1L
#undef com_meizu_jni_JniUtil_UPLOAD_SIGN_TYPE
#define com_meizu_jni_JniUtil_UPLOAD_SIGN_TYPE 2L
#undef com_meizu_jni_JniUtil_GAME_SIGN_TYPE
#define com_meizu_jni_JniUtil_GAME_SIGN_TYPE 3L
#undef com_meizu_jni_JniUtil_DEBUG
#define com_meizu_jni_JniUtil_DEBUG 1L
/*
 * Class:     com_meizu_jni_JniUtil
 * Method:    encrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_meizu_jni_JniUtil_encrypt
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_meizu_jni_JniUtil
 * Method:    getAppSignKey
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_meizu_jni_JniUtil_getAppSignKey
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
