/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_othershe_jnitest_JniUtil */

#ifndef _Included_com_othershe_jnitest_JniUtil
#define _Included_com_othershe_jnitest_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_othershe_jnitest_JniUtil
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_othershe_jnitest_JniUtil_encrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
