/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_othershe_jnitest_JniUtil */

#ifndef _Included_com_othershe_jnitest_JniUtil
#define _Included_com_othershe_jnitest_JniUtil
#ifdef __cplusplus
extern "C" {
#endif


__const char* priv_key ="[.7=a$K#z)d3Eu^P";

__const char* iv_key ="_g7=a$K#)d*E#fg7";

__const char*  CIPHER_ALGORITHM = "AES/CBC/PKCS5Padding";

__const char* KEY_ALGORITHM = "AES";

static jclass stringClass;
/*
 * Class:     com_othershe_jnitest_JniUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_othershe_jnitest_JniUtil_test
  (JNIEnv *, jobject);

/*
 * Class:     com_othershe_jnitest_JniUtil
 * Method:    StrEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_othershe_jnitest_JniUtil_StrEncrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_othershe_jnitest_JniUtil
 * Method:    byteEncrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_othershe_jnitest_JniUtil_byteEncrypt
  (JNIEnv *, jobject, jbyteArray);

JNIEXPORT jstring stoJstring(JNIEnv* , jbyteArray );

#ifdef __cplusplus
}
#endif
#endif
