/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yangjingan_ndkresearch_JniUtil */

#ifndef _Included_com_example_yangjingan_ndkresearch_JniUtil
#define _Included_com_example_yangjingan_ndkresearch_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yangjingan_ndkresearch_JniUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yangjingan_ndkresearch_JniUtil_test
  (JNIEnv *, jobject);

/*
 * Class:     com_example_yangjingan_ndkresearch_JniUtil
 * Method:    AesEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yangjingan_ndkresearch_JniUtil_AesEncrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
